steps:
- name: 'gcr.io/k8s-skaffold/skaffold'
  id: build-and-test
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build and push images
    skaffold build --file-output=/workspace/artifacts.json \
                   --default-repo gcr.io/$PROJECT_ID \
                   --push=true
    # Test images
    #skaffold test --build-artifacts=/workspace/artifacts.json
- name: 'google/cloud-sdk:latest'
  id: create-release
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region us-central1
    gcloud alpha deploy apply --file pipeline.yaml
    gcloud alpha deploy apply --file staging.yaml
    gcloud alpha deploy apply --file prod.yaml
    gcloud alpha deploy releases create $SHORT_SHA-$(date +%s) \
                        --delivery-pipeline sample-app \
                        --description "$(git log -1  --pretty='%s')" \
                        --region us-central1 \
                        --build-artifacts /workspace/artifacts.json
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-gceme-artifacts/'
    paths:
    - '/workspace/artifacts.json'
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
