#Defines the sequence of the delivery pipeline
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: <name-of-delivery-pipeline>
description: main application DeliveryPipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
 - targetId: test
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: dev
description: development cluster
gkeCluster:

 project: <project-id>
 cluster: <name-of-dev-cluster>
 location: us-central1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: test
description: testing cluster
gkeCluster:

 project: <project-id>
 cluster: <name-of-test-cluster>
 location: us-central1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gkeCluster:

 project: <project-id>
 cluster: <name-of-prod-cluster>
 location: us-central1 