steps:

# clone the latest source codes 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['gcloud source repos clone','github_vibhakurpad_flutterwebapp --project=akshay-poc']
  dir: '/workspace'

# using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/$PROJECT_ID/flutter'
  entrypoint: '/bin/bash'
  args: ['build.sh', 'Flutter']