apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: cicd-demo
description: main application DeliveryPipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
 - targetId: test
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: dev
description: development cluster
gkeCluster:

 project: vibhak-cicd-project
 cluster: dev-cluster
 location: us-central1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: test
description: testing cluster
gkeCluster:

 project: vibhak-cicd-project
 cluster: test-cluster
 location: us-central1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gkeCluster:

 project: vibhak-cicd-project
 cluster: prod-cluster
 location: us-central1 