# Flutter CD configuration file with Cloud build

steps:

# clone the latest source codes 
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/VibhaKurpad/Flutter.git']
  dir: '/workspace'

# using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/$PROJECT_ID/flutter'
  entrypoint: '/bin/bash'
  args: ['build.sh', 'Flutter']

# upload apk to Google Cloud Storage bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','/workspace/Flutter/build/app/outputs/apk/release/app-release.apk', 'gs://vibha-flutterapp/app-debug-$SHORT_SHA.apk']