steps:

# clone the latest source codes 
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://source.developers.google.com/p/akshayk-poc/r/github_vibhakurpad_flutterwebapp']
  dir: '/workspace'

# using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/$PROJECT_ID/flutter'
  entrypoint: '/bin/bash'
  args: ['build.sh', 'Flutter']