apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: sample-app
description: main application DeliveryPipeline
serialPipeline:
 stages:
 - targetId: staging
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: staging
description: staging cluster
gkeCluster:

 project: akshayk-poc
 cluster: cd-staging
 location: us-central1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: prod cluster
gkeCluster:

 project: akshayk-poc
 cluster: cd-prod
 location: us-central1 