aapiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: sample-app
description: sample-app delivery pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles:
    - staging
  - targetId: prod
    profiles:
    - prod
