apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
- resourceType: service
  resourceName: sample-app-dev
  port: 8080
