apiVersion: v1
kind: Service
metadata:
  name: skaffold-example
  labels: 
    app: skaffold-example
spec:
  selector:
    app: skaffold-example
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-example
  labels:
    app: skaffold-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-example
  template:
    metadata:
      labels:
        app: skaffold-example
    spec:
      containers:
      - name: skaffold-example
        image: gcr.io/akshayk-poc/skaffold-example@sha256:dcb2c560ce0af61412c7f6e810f6924735cf84edd32d32db8f8e88be024b4900
        ports:
        - containerPort: 8080
