apiVersion: v1
kind: Service
metadata:
  name: <name-of-image>
  labels: 
    app: <name-of-image>
spec:
  selector:
    app: <name-of-image>
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name-of-image>
  labels:
    app: <name-of-image>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <name-of-image>
  template:
    metadata:
      labels:
        app: <name-of-image>
    spec:
      containers:
      - name: <name-of-image>
        image: <path-to-image>
        ports:
        - containerPort: 8080
